import { Inter } from "next/font/google";
import "./styles/globals.css";
import TheHeader from "../components/TheHeader";
import TheFooter from "../components/TheFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TheHeader/>
      <main>
          {children}
      </main>
      <TheFooter/>
      </body>
    </html>
  );
}
