import { Inter, Montserrat } from "next/font/google";
import "./styles/globals.css";
import TheHeader from "../components/organisms/theHeader/TheHeader";
import TheFooter from "../components/TheFooter";
import React from "react";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${inter.className} ${montserrat.variable}`}>
      <div style={{display: 'flex', flexDirection: 'column', minHeight: '100vh'}}>
          <TheHeader/>
          <main style={{flexGrow: 1}}>
              {children}
          </main>
          <TheFooter/>
      </div>
      </body>
    </html>
  );
}
